CREATE TABLE CLIENT (
    ID NUMBER,
    NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PASSWORD VARCHAR(25),
    PRIMARY KEY (ID)
);

INSERT INTO CLIENT (ID, NAME, EMAIL, PASSWORD) VALUES
(1, 'JD', 'jd@gmail.com', '123456')